### PR TITLE
Add about

### LINKED ISSUE #16: About Page
image

When I go to the settings, I would like to see

- [ ] the license
- [ ] the link to the source, clickable to open the page
- [ ] the version information

I wonder how to implement this: Maybe embed a view with the content ? It does not seem right to put this into the preferences.

See also: https://github.com/fixme-lausanne/MyHackerspace/issues/86

### PR DESCRIPTION
**Pull request by niccokunzmann**
This fixes #16.

image

### CODE REVIEW

**Comment by dbrgn** [comment]
Hi, thanks for the PR. I have another idea, how this would be solved better: I wouldn't look for the "about" information in the settings. Instead of showing the three fixed icons in the top right, add a menu to the action bar. In `src/res/menu/main.xml`:

```xml
    <item
        android:id="@+id/menu_about"
        android:icon="@drawable/ic_TODO"
        android:showAsAction="never"
        android:title="@string/btn_about"/>
```

When the user taps on this menu entry, a dedicated about activity is shown. The license information should also be part of that about screen.

screenshot-20220903-120922

screenshot-20220903-120932

What do you think? Would you like to implement this?

**Comment by niccokunzmann** [comment]
I am happy to see a menu. I do not know when I will get to this or who will. The code is quite modular and it can be moved. Personally, I would merge it and create a new issue to create a menu - this change is better than before but not perfect - in my eyes. It might be that this fix will not be shipped for a while if it is not merged. But that is also your decision as a maintainer.

My maintenance style would be hopefully "Done is better than perfect" & "small steps with fast feedback" and for community: "engaged and merged (and reverted) is better than rejected/stale" - but they have to be weighted with long-term maintainability - so your choice as the maintainer!

I am too tired to do it now properly.

**Comment by dbrgn** [comment]
There are a few issues with this PR:

- Layout: The left alignment of the menu entry is incorrect
- Layout nitpick: Missing space after the colons
- A lot of unused imports
- At least on my test device (Emulator with API 31), the button pointing to the repository doesn't work

A lot of this is due to the approach of putting content into the settings view, which isn't made for that. This results in things like having to write a custom layout, just to wrap the content.

As for the button, I'm not sure if the approach of just putting the URL into an intent is valid at all. It probably depends on the Android version, whether this works or not. A much easier approach is simply making the URL in the text view clickable.

I rebased your branch on top of current `main`, removed unrelated changes (like the Gradle update) and will fix some of the issues above directly in this branch. The move to a separate activity can then be done in separate MRs.

**Comment by dbrgn** [comment]
Doesn't look too bad now!

image

**Pull request merged**
