### PR TITLE
correct link to f-droid

### PR DESCRIPTION
**Pull request by niccokunzmann**
Once F-Droid has released the new app, it would be good to merge this to get the new link at the f-droid image.

### CODE REVIEW

**Comment by Poussinou** [comment]
@niccokunzmann The good link is https://f-droid.org/packages/io.spaceapi.myhackerspace/

The ID of the app is not the same on F-Droid

**Comment by niccokunzmann** [comment]
https://f-droid.org/packages/io.spaceapi.myhackerspace/ could be the link - for now, we need to wait until it is published.
According to https://mastodon.technology/@IzzyOnDroid/108799995661264769 the update is in progress.

**Comment by niccokunzmann** [comment]
Would you like me to use this link instead: https://f-droid.org/en/packages/io.spaceapi.community.myhackerspace/ ?

**Comment by Poussinou** [comment]
> Would you like me to use this link instead: https://f-droid.org/en/packages/io.spaceapi.community.myhackerspace/ ?

https://f-droid.org/packages/io.spaceapi.community.myhackerspace/ (without "en") is the good link indeed, sorry.

**Comment by niccokunzmann** [comment]
I removed the `en`

**Comment by dbrgn** [comment]
@niccokunzmann thanks for the submission. As mentioned in #14, I never got notifications. The change (dropping the `en`) looks good, but the README has changed in the meantime. To get this change merged quickly, I updated the README myself in #29 (but added you as co-author of the commit).

**Pull request closed without merging**
