### PR TITLE
Timestamp formatting

### LINKED ISSUE #46: display lastchange timestamp as formatted string
Hi, I've discovered this app today and it's quite handy, but I wish that it would display the lastchange unix timestamp (for the status) in a more human-readable datetime format, preferably with both absolute and relative specifications (i.e. <dd-mm-yyyy, hh:mm> (<x hours ago | y days ago etc>)

### PR DESCRIPTION
**Pull request by dbrgn**
Show state "last change" timestamp as localized datetime.

Fixes #46.

### CODE REVIEW

**Comment by dbrgn** [comment]
(In case building fails, this is probably because the latest `spaceapi-kt` release did not yet propagate to the production Maven Central servers.)

**Comment by niccokunzmann** [comment]
True. How long does this take?

**Comment by dbrgn** [comment]
Works now. (Usually takes around an hour.)

**Comment by niccokunzmann** [comment]
For me, increasing the API level is important to document in the changelog.
The reason: I often use old and recycled phones. Increasing the minimum API level excludes users.

**Comment by dbrgn** [comment]
It already is part of the changelog, see diff 🙂

**Comment by NANASHI0X74** [comment]
when will this be released? I'd really like to have this feature- as of now I keep copying the lastchange and pasting it in [epochconverter](https://www.epochconverter.com/) online, which is a bit of a pain

**Comment by niccokunzmann** [comment]
Good question. I wonder what the release process looks like. I guess, F-droid just uses tags.

**Comment by dbrgn** [comment]
I'm in vacations right now until mid-October. I have the Google Play signing key at home. For F-Droid however, I think a version bump and tag should be sufficient. I can do that in the coming 2-3 days.

Am Fr, 29. Sep 2023, um 13:58, schrieb Nicco Kunzmann:

**Comment by dbrgn** [comment]
Done. Now we need to wait for F-Droid to pick up the new tag.

**Pull request merged**
