### PR TITLE
23 fix slow load

### LINKED ISSUE #23: Very slow loading when adding widget to homescreen
When I try to create a widget the app shows loading. I can tap the loading icon away but can't choose a hackerspace.

### PR DESCRIPTION
**Pull request by niccokunzmann**
this loads the widget instantly

- refactor widget loading into method
- call method additionally to android OS redirected unreliable alarm

fixes #23

### CODE REVIEW

**Comment by niccokunzmann** [comment]
What happens is that the Widget is created with an ID, then the Widget_config is invoked with this ID. It created the Activity.
There, the OK button saves the preferences and commits them.
This activity is responsible to creating an Update.

The prior implementation relies on the system update mechanism which is documented to be unreliable: `setInexactRepeating`.
Now, reliability is introduced by calling an update.

The other two commits were experimentation. I reverted it but have a look if you like.

**Comment by niccokunzmann** [comment]
@dbrgn could you leave a comment on this PR?

**Comment by dbrgn** [comment]
Thanks! I haven't tested this thoroughly, but the widget does seem to load fine. (I'm not much of a widget user myself, but for now I added it to my home screen for testing purposes.)

I'll rebase this PR against `main` (I'll remove the commits 2 and 3 in that step, since changes were reverted anyways) and will merge it afterwards.

**Comment by dbrgn** [comment]
Ah, I just (re)read your comment where you said that you'd like to keep the reverted commit in the history. I assume for reference? I'm not sure how much value that brings, as long as the revert commit doesn't contain any information, _why_ the change was reverted, so someone casually looking at the history won't know.

However, I do think it's good to have things like these be discoverable, so let's include the diff here instead, so that it can be found through GitHub issue search:

```diff
commit a7f1dcfe4483147144d44e36d7350767af02768e
Date:   Mon Sep 5 01:27:51 2022 +0100

    add more receivers for widget update

    - make receivers public so that everyone can access them
    - add receiver for first creation of widget

diff --git a/app/src/main/AndroidManifest.xml b/app/src/main/AndroidManifest.xml
index 069b667..27e50f6 100644
--- a/app/src/main/AndroidManifest.xml
+++ b/app/src/main/AndroidManifest.xml
@@ -59,11 +59,15 @@

         <receiver
             android:name=".Widget"
-            android:exported="false">
+            android:exported="true">
             <intent-filter>
                 <action android:name="android.appwidget.action.APPWIDGET_UPDATE" />
             </intent-filter>

+            <intent-filter>
+                <action android:name="android.appwidget.action.APPWIDGET_ENABLED" />
+            </intent-filter>
+
             <intent-filter>
                 <action android:name="android.intent.action.ACTION_BOOT_COMPLETED" />
             </intent-filter>
```

**Pull request merged**
