### PR TITLE
Upgrade spaceapi-kt to 0.4.1

### PR DESCRIPTION
**Pull request by dbrgn**
This fixes a parsing bug for certain endpoints.
See https://github.com/spaceapi-community/spaceapi-kt/pull/35

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Cool. Do we have CI tests, yet?

**Comment by dbrgn** [comment]
Some unit tests, yes: https://app.circleci.com/pipelines/github/spaceapi-community/my-hackerspace/82/workflows/6d4df2c9-1db4-4e9c-9e51-0f9ce9571abd (You should see the pipeline if you log in with GitHub.)

The regression test is part of https://github.com/spaceapi-community/spaceapi-kt/pull/35 though, we don't test parsing in the MyHackerspace testsuite.

**Comment by niccokunzmann** [comment]
I looked at this: https://app.circleci.com/pipelines/github/spaceapi-community/my-hackerspace/82/workflows/6d4df2c9-1db4-4e9c-9e51-0f9ce9571abd/jobs/79/parallel-runs/0/steps/0-105

I think, there are no unit tests.

I totally agree with the change. I think, I can use this as a chance to find out more about the app.
I will have a look of there are supposed to be unit tests running.

**Comment by niccokunzmann** [comment]
Ilook at it with the octodroid app. Ot looks a bit different.

**Comment by dbrgn** [comment]
There is currently one unit test here: https://github.com/spaceapi-community/my-hackerspace/blob/main/app/src/test/java/io/spaceapi/community/myhackerspace/UtilsTest.java

The output of Gradle for tests is quite messy. It's easier if you look at it in your IDE. (Main job of CI is to alert if a test fails, and that should work fine.)

**Comment by niccokunzmann** [comment]
Oh,I found it. I did not expect them to end up in one line.

They probably use \r. I wonder if curcle CI can displaythat as a newline.
`
EXECUTING [39s]> :app:testDebugUnitTest > 1 `

There is only one test.

**Review by niccokunzmann — APPROVED** [review]
Yes, I found the test and I understand the workflow. Thanks for your patience!

**Comment by niccokunzmann** [comment]
Hm. I cannot click merge.

**Comment by dbrgn** [comment]
> Hm. I cannot click merge.

I fixed the permissions, it should be possible now.

Regarding the mode of merging, I usually prefer this flow:

- If it's a single commit, squash and merge
- If there are multiple commits in a PR, merge with a merge commit

Regarding the question _who_ merges, there are two approaches: The PR creator merges after approval, or anyone can merge if approved. I used to prefer the first variant, but in the meantime I don't have a strong opinion anymore. The latter is probably more efficient, so feel free to merge!

**Pull request merged**
